services:
  book_service:
    build: ./book_service
    ports:
      - "5001:5001"

  user_service:
    build: ./user_service
    ports:
      - "5002:5002"

  order_service:
    build: ./order_service
    ports:
      - "5003:5003"

  payment_service:
    build: ./payment_service
    ports:
      - "5004:5004"
